
# This file is automatically generated, you probably don't want to edit this

analyzedesignOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "analyzedesignOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            responses = NULL,
            factors = NULL,
            pooledFactor = NULL,
            method = "regression",
            model = "main2fi",
            customTerms = "",
            excludeTerms = "",
            effectFDR = FALSE,
            effectSummary = TRUE,
            goal = "maximize",
            target = 0,
            snType = "auto",
            snModel = TRUE,
            plotSN = TRUE,
            plotMeans = TRUE,
            halfNormal = TRUE,
            pareto = TRUE,
            mainEffects = FALSE,
            interaction = FALSE,
            residuals = TRUE,
            contour = FALSE, ...) {

            super$initialize(
                package="jmvdoe",
                name="analyzedesign",
                requiresData=TRUE,
                ...)

            private$..responses <- jmvcore::OptionVariables$new(
                "responses",
                responses,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..pooledFactor <- jmvcore::OptionVariable$new(
                "pooledFactor",
                pooledFactor,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "regression",
                    "taguchi"),
                default="regression")
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "main",
                    "main2fi",
                    "rsm",
                    "custom"),
                default="main2fi")
            private$..customTerms <- jmvcore::OptionString$new(
                "customTerms",
                customTerms,
                default="")
            private$..excludeTerms <- jmvcore::OptionString$new(
                "excludeTerms",
                excludeTerms,
                default="")
            private$..effectFDR <- jmvcore::OptionBool$new(
                "effectFDR",
                effectFDR,
                default=FALSE)
            private$..effectSummary <- jmvcore::OptionBool$new(
                "effectSummary",
                effectSummary,
                default=TRUE)
            private$..goal <- jmvcore::OptionList$new(
                "goal",
                goal,
                options=list(
                    "maximize",
                    "minimize",
                    "match"),
                default="maximize")
            private$..target <- jmvcore::OptionNumber$new(
                "target",
                target,
                default=0)
            private$..snType <- jmvcore::OptionList$new(
                "snType",
                snType,
                options=list(
                    "auto",
                    "smaller",
                    "larger",
                    "nominal"),
                default="auto")
            private$..snModel <- jmvcore::OptionBool$new(
                "snModel",
                snModel,
                default=TRUE)
            private$..plotSN <- jmvcore::OptionBool$new(
                "plotSN",
                plotSN,
                default=TRUE)
            private$..plotMeans <- jmvcore::OptionBool$new(
                "plotMeans",
                plotMeans,
                default=TRUE)
            private$..halfNormal <- jmvcore::OptionBool$new(
                "halfNormal",
                halfNormal,
                default=TRUE)
            private$..pareto <- jmvcore::OptionBool$new(
                "pareto",
                pareto,
                default=TRUE)
            private$..mainEffects <- jmvcore::OptionBool$new(
                "mainEffects",
                mainEffects,
                default=FALSE)
            private$..interaction <- jmvcore::OptionBool$new(
                "interaction",
                interaction,
                default=FALSE)
            private$..residuals <- jmvcore::OptionBool$new(
                "residuals",
                residuals,
                default=TRUE)
            private$..contour <- jmvcore::OptionBool$new(
                "contour",
                contour,
                default=FALSE)

            self$.addOption(private$..responses)
            self$.addOption(private$..factors)
            self$.addOption(private$..pooledFactor)
            self$.addOption(private$..method)
            self$.addOption(private$..model)
            self$.addOption(private$..customTerms)
            self$.addOption(private$..excludeTerms)
            self$.addOption(private$..effectFDR)
            self$.addOption(private$..effectSummary)
            self$.addOption(private$..goal)
            self$.addOption(private$..target)
            self$.addOption(private$..snType)
            self$.addOption(private$..snModel)
            self$.addOption(private$..plotSN)
            self$.addOption(private$..plotMeans)
            self$.addOption(private$..halfNormal)
            self$.addOption(private$..pareto)
            self$.addOption(private$..mainEffects)
            self$.addOption(private$..interaction)
            self$.addOption(private$..residuals)
            self$.addOption(private$..contour)
        }),
    active = list(
        responses = function() private$..responses$value,
        factors = function() private$..factors$value,
        pooledFactor = function() private$..pooledFactor$value,
        method = function() private$..method$value,
        model = function() private$..model$value,
        customTerms = function() private$..customTerms$value,
        excludeTerms = function() private$..excludeTerms$value,
        effectFDR = function() private$..effectFDR$value,
        effectSummary = function() private$..effectSummary$value,
        goal = function() private$..goal$value,
        target = function() private$..target$value,
        snType = function() private$..snType$value,
        snModel = function() private$..snModel$value,
        plotSN = function() private$..plotSN$value,
        plotMeans = function() private$..plotMeans$value,
        halfNormal = function() private$..halfNormal$value,
        pareto = function() private$..pareto$value,
        mainEffects = function() private$..mainEffects$value,
        interaction = function() private$..interaction$value,
        residuals = function() private$..residuals$value,
        contour = function() private$..contour$value),
    private = list(
        ..responses = NA,
        ..factors = NA,
        ..pooledFactor = NA,
        ..method = NA,
        ..model = NA,
        ..customTerms = NA,
        ..excludeTerms = NA,
        ..effectFDR = NA,
        ..effectSummary = NA,
        ..goal = NA,
        ..target = NA,
        ..snType = NA,
        ..snModel = NA,
        ..plotSN = NA,
        ..plotMeans = NA,
        ..halfNormal = NA,
        ..pareto = NA,
        ..mainEffects = NA,
        ..interaction = NA,
        ..residuals = NA,
        ..contour = NA)
)

analyzedesignResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "analyzedesignResults",
    inherit = jmvcore::Group,
    active = list(
        analysisInfo = function() private$.items[["analysisInfo"]],
        analysisEffects = function() private$.items[["analysisEffects"]],
        analysisEffectPlot = function() private$.items[["analysisEffectPlot"]],
        analysisAnova = function() private$.items[["analysisAnova"]],
        analysisCoef = function() private$.items[["analysisCoef"]],
        analysisRecommend = function() private$.items[["analysisRecommend"]],
        analysisPerRun = function() private$.items[["analysisPerRun"]],
        analysisResponseSN = function() private$.items[["analysisResponseSN"]],
        analysisResponseMean = function() private$.items[["analysisResponseMean"]],
        analysisSnDelta = function() private$.items[["analysisSnDelta"]],
        analysisSnPredict = function() private$.items[["analysisSnPredict"]],
        analysisSnAnova = function() private$.items[["analysisSnAnova"]],
        analysisHalfNormal = function() private$.items[["analysisHalfNormal"]],
        analysisPareto = function() private$.items[["analysisPareto"]],
        analysisMainEffects = function() private$.items[["analysisMainEffects"]],
        analysisInteraction = function() private$.items[["analysisInteraction"]],
        analysisResiduals = function() private$.items[["analysisResiduals"]],
        analysisContour = function() private$.items[["analysisContour"]],
        analysisPlotSN = function() private$.items[["analysisPlotSN"]],
        analysisPlotMeans = function() private$.items[["analysisPlotMeans"]],
        analysisSnDeltaPlot = function() private$.items[["analysisSnDeltaPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analyze Design")
            self$add(jmvcore::Html$new(
                options=options,
                name="analysisInfo",
                title="Model Summary",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisEffects",
                title="Effect Summary",
                visible="(method:regression && effectSummary)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="response", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="term", 
                        `title`="Source", 
                        `type`="text"),
                    list(
                        `name`="logworth", 
                        `title`="Logworth", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="PValue", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisEffectPlot",
                title="Effect Summary Plot",
                width=500,
                height=400,
                renderFun=".plotEffectSummary",
                visible="(method:regression && effectSummary)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisAnova",
                title="ANOVA",
                visible="(method:regression)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="response", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="ss", 
                        `title`="Sum of Squares", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="ms", 
                        `title`="Mean Square", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisCoef",
                title="Coefficients",
                visible="(method:regression)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="response", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisRecommend",
                title="Preferred settings",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="response", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="goal", 
                        `title`="Goal", 
                        `type`="text"),
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Preferred level", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisPerRun",
                title="Per-run SN and Mean",
                visible="(method:taguchi)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="run", 
                        `title`="Run", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sn", 
                        `title`="SN", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisResponseSN",
                title="Response Table (SN)",
                visible="(method:taguchi)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="meanSN", 
                        `title`="Mean SN", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisResponseMean",
                title="Response Table (Means)",
                visible="(method:taguchi)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="meanY", 
                        `title`="Mean Response", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisSnDelta",
                title="SN Delta and Rank",
                visible="(method:taguchi)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="delta", 
                        `title`="Delta", 
                        `type`="number"),
                    list(
                        `name`="rank", 
                        `title`="Rank", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisSnPredict",
                title="Predicted SN",
                visible="(method:taguchi)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="sn", 
                        `title`="SN", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisSnAnova",
                title="ANOVA on SN",
                visible="(method:taguchi && snModel)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="ss", 
                        `title`="Sum of Squares", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="ms", 
                        `title`="Mean Square", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="contrib", 
                        `title`="Contribution %", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisHalfNormal",
                title="Half-Normal Plot",
                width=450,
                height=400,
                renderFun=".plotHalfNormal",
                visible="(method:regression && halfNormal)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisPareto",
                title="Pareto Plot",
                width=450,
                height=400,
                renderFun=".plotPareto",
                visible="(method:regression && pareto)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisMainEffects",
                title="Main Effects Plot",
                width=500,
                height=400,
                renderFun=".plotMainEffects",
                visible="(method:regression && mainEffects)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisInteraction",
                title="Interaction Plot",
                width=450,
                height=400,
                renderFun=".plotInteraction",
                visible="(method:regression && interaction)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisResiduals",
                title="Residual Plots",
                width=500,
                height=400,
                renderFun=".plotResiduals",
                visible="(method:regression && residuals)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisContour",
                title="Contour Plot",
                width=450,
                height=400,
                renderFun=".plotContour",
                visible="(method:regression && contour)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisPlotSN",
                title="SN Main Effects",
                width=500,
                height=400,
                renderFun=".plotSN",
                visible="(method:taguchi && plotSN)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisPlotMeans",
                title="Means Main Effects",
                width=500,
                height=400,
                renderFun=".plotMeans",
                visible="(method:taguchi && plotMeans)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisSnDeltaPlot",
                title="SN Factor Delta",
                width=450,
                height=400,
                renderFun=".plotSnDelta",
                visible="(method:taguchi)",
                clearWith=list(
                    "responses",
                    "factors",
                    "pooledFactor",
                    "method",
                    "model",
                    "customTerms",
                    "excludeTerms",
                    "effectFDR",
                    "effectSummary",
                    "goal",
                    "target",
                    "snType")))}))

analyzedesignBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "analyzedesignBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvdoe",
                name = "analyzedesign",
                version = c(1,0,0),
                options = options,
                results = analyzedesignResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Analyze Design
#'
#' Fit a model to measured results after you have run the experiment. Use 
#' regression / ANOVA (effect summary, Type III logworth, plots, preferred 
#' settings) or Taguchi signal-to-noise analysis, including SN delta and rank, 
#' percent contribution, and a predicted SN at the preferred settings. Move 
#' the measured columns into Responses and the design columns into Factors.
#' @param data the data as a data frame
#' @param responses the measured response column(s) to model
#' @param factors the design factor columns
#' @param pooledFactor a factor whose variation is treated as error in the
#'   Taguchi S/N ANOVA, rather than tested
#' @param method .
#' @param model .
#' @param customTerms .
#' @param excludeTerms comma-separated model terms to drop before fitting,
#'   using the names shown in Effect Summary (for example Temp:Time or
#'   Temp*Time)
#' @param effectFDR compute Effect Summary logworth from BH
#'   false-discovery-rate adjusted p-values
#' @param effectSummary .
#' @param goal .
#' @param target .
#' @param snType .
#' @param snModel .
#' @param plotSN .
#' @param plotMeans .
#' @param halfNormal .
#' @param pareto .
#' @param mainEffects .
#' @param interaction .
#' @param residuals .
#' @param contour .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$analysisInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$analysisEffects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisEffectPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisAnova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisCoef} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisRecommend} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisPerRun} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisResponseSN} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisResponseMean} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisSnDelta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisSnPredict} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisSnAnova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisHalfNormal} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisPareto} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisMainEffects} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisInteraction} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisResiduals} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisPlotSN} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisPlotMeans} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisSnDeltaPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$analysisEffects$asDF}
#'
#' \code{as.data.frame(results$analysisEffects)}
#'
#' @export
analyzedesign <- function(
    data,
    responses,
    factors,
    pooledFactor = NULL,
    method = "regression",
    model = "main2fi",
    customTerms = "",
    excludeTerms = "",
    effectFDR = FALSE,
    effectSummary = TRUE,
    goal = "maximize",
    target = 0,
    snType = "auto",
    snModel = TRUE,
    plotSN = TRUE,
    plotMeans = TRUE,
    halfNormal = TRUE,
    pareto = TRUE,
    mainEffects = FALSE,
    interaction = FALSE,
    residuals = TRUE,
    contour = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("analyzedesign requires jmvcore to be installed (restart may be required)")

    if ( ! missing(responses)) responses <- jmvcore::resolveQuo(jmvcore::enquo(responses))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(pooledFactor)) pooledFactor <- jmvcore::resolveQuo(jmvcore::enquo(pooledFactor))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(responses), responses, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(pooledFactor), pooledFactor, NULL))


    options <- analyzedesignOptions$new(
        responses = responses,
        factors = factors,
        pooledFactor = pooledFactor,
        method = method,
        model = model,
        customTerms = customTerms,
        excludeTerms = excludeTerms,
        effectFDR = effectFDR,
        effectSummary = effectSummary,
        goal = goal,
        target = target,
        snType = snType,
        snModel = snModel,
        plotSN = plotSN,
        plotMeans = plotMeans,
        halfNormal = halfNormal,
        pareto = pareto,
        mainEffects = mainEffects,
        interaction = interaction,
        residuals = residuals,
        contour = contour)

    analysis <- analyzedesignClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

