
# This file is automatically generated, you probably don't want to edit this

customdesignOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "customdesignOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factors = list(),
            model = "main",
            criterion = "D",
            nRuns = 12,
            replicates = 1,
            randomize = TRUE,
            seed = 1,
            responses = list(),
            responseTarget = 0,
            simulateResponses = TRUE,
            evaluateDesign = FALSE,
            halfNormal = TRUE,
            pareto = TRUE,
            mainEffects = FALSE,
            interaction = FALSE,
            residuals = TRUE,
            contour = FALSE,
            addToSpreadsheet = FALSE, ...) {

            super$initialize(
                package="jmvdoe",
                name="customdesign",
                requiresData=TRUE,
                ...)

            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "continuous",
                                "categorical"),
                            default="continuous"),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL,
                            default="-1, 1"))))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "main",
                    "main2fi",
                    "rsm"),
                default="main")
            private$..criterion <- jmvcore::OptionList$new(
                "criterion",
                criterion,
                options=list(
                    "D",
                    "I"),
                default="D")
            private$..nRuns <- jmvcore::OptionInteger$new(
                "nRuns",
                nRuns,
                min=4,
                default=12)
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                min=1,
                default=1)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize,
                default=TRUE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=1)
            private$..responses <- jmvcore::OptionArray$new(
                "responses",
                responses,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "responses",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionList$new(
                            "goal",
                            NULL,
                            options=list(
                                "maximize",
                                "minimize",
                                "match"),
                            default="maximize"),
                        jmvcore::OptionNumber$new(
                            "target",
                            NULL,
                            default=0))))
            private$..responseTarget <- jmvcore::OptionNumber$new(
                "responseTarget",
                responseTarget,
                default=0,
                hidden=TRUE)
            private$..simulateResponses <- jmvcore::OptionBool$new(
                "simulateResponses",
                simulateResponses,
                default=TRUE)
            private$..evaluateDesign <- jmvcore::OptionBool$new(
                "evaluateDesign",
                evaluateDesign,
                default=FALSE)
            private$..halfNormal <- jmvcore::OptionBool$new(
                "halfNormal",
                halfNormal,
                default=TRUE)
            private$..pareto <- jmvcore::OptionBool$new(
                "pareto",
                pareto,
                default=TRUE)
            private$..mainEffects <- jmvcore::OptionBool$new(
                "mainEffects",
                mainEffects,
                default=FALSE)
            private$..interaction <- jmvcore::OptionBool$new(
                "interaction",
                interaction,
                default=FALSE)
            private$..residuals <- jmvcore::OptionBool$new(
                "residuals",
                residuals,
                default=TRUE)
            private$..contour <- jmvcore::OptionBool$new(
                "contour",
                contour,
                default=FALSE)
            private$..addToSpreadsheet <- jmvcore::OptionAction$new(
                "addToSpreadsheet",
                addToSpreadsheet)
            private$..designOutput <- jmvcore::OptionOutput$new(
                "designOutput")

            self$.addOption(private$..factors)
            self$.addOption(private$..model)
            self$.addOption(private$..criterion)
            self$.addOption(private$..nRuns)
            self$.addOption(private$..replicates)
            self$.addOption(private$..randomize)
            self$.addOption(private$..seed)
            self$.addOption(private$..responses)
            self$.addOption(private$..responseTarget)
            self$.addOption(private$..simulateResponses)
            self$.addOption(private$..evaluateDesign)
            self$.addOption(private$..halfNormal)
            self$.addOption(private$..pareto)
            self$.addOption(private$..mainEffects)
            self$.addOption(private$..interaction)
            self$.addOption(private$..residuals)
            self$.addOption(private$..contour)
            self$.addOption(private$..addToSpreadsheet)
            self$.addOption(private$..designOutput)
        }),
    active = list(
        factors = function() private$..factors$value,
        model = function() private$..model$value,
        criterion = function() private$..criterion$value,
        nRuns = function() private$..nRuns$value,
        replicates = function() private$..replicates$value,
        randomize = function() private$..randomize$value,
        seed = function() private$..seed$value,
        responses = function() private$..responses$value,
        responseTarget = function() private$..responseTarget$value,
        simulateResponses = function() private$..simulateResponses$value,
        evaluateDesign = function() private$..evaluateDesign$value,
        halfNormal = function() private$..halfNormal$value,
        pareto = function() private$..pareto$value,
        mainEffects = function() private$..mainEffects$value,
        interaction = function() private$..interaction$value,
        residuals = function() private$..residuals$value,
        contour = function() private$..contour$value,
        addToSpreadsheet = function() private$..addToSpreadsheet$value,
        designOutput = function() private$..designOutput$value),
    private = list(
        ..factors = NA,
        ..model = NA,
        ..criterion = NA,
        ..nRuns = NA,
        ..replicates = NA,
        ..randomize = NA,
        ..seed = NA,
        ..responses = NA,
        ..responseTarget = NA,
        ..simulateResponses = NA,
        ..evaluateDesign = NA,
        ..halfNormal = NA,
        ..pareto = NA,
        ..mainEffects = NA,
        ..interaction = NA,
        ..residuals = NA,
        ..contour = NA,
        ..addToSpreadsheet = NA,
        ..designOutput = NA)
)

customdesignResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "customdesignResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        design = function() private$.items[["design"]],
        efficiency = function() private$.items[["efficiency"]],
        analysisInfo = function() private$.items[["analysisInfo"]],
        analysisAnova = function() private$.items[["analysisAnova"]],
        analysisCoef = function() private$.items[["analysisCoef"]],
        analysisRecommend = function() private$.items[["analysisRecommend"]],
        analysisHalfNormal = function() private$.items[["analysisHalfNormal"]],
        analysisPareto = function() private$.items[["analysisPareto"]],
        analysisMainEffects = function() private$.items[["analysisMainEffects"]],
        analysisInteraction = function() private$.items[["analysisInteraction"]],
        analysisResiduals = function() private$.items[["analysisResiduals"]],
        analysisContour = function() private$.items[["analysisContour"]],
        designOutput = function() private$.items[["designOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Custom Design")
            self$add(jmvcore::Html$new(
                options=options,
                name="info",
                title="Design Summary",
                clearWith=list(
                    "factors",
                    "model",
                    "criterion",
                    "nRuns",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Table$new(
                options=options,
                name="design",
                title="Design Table",
                clearWith=list(
                    "factors",
                    "model",
                    "criterion",
                    "nRuns",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="Run", 
                        `title`="Run", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="efficiency",
                title="Design Efficiency",
                clearWith=list(
                    "factors",
                    "model",
                    "criterion",
                    "nRuns",
                    "randomize",
                    "seed")))
            self$add(jmvcore::Html$new(
                options=options,
                name="analysisInfo",
                title="Model Summary",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisAnova",
                title="ANOVA",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="response", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="ss", 
                        `title`="Sum of Squares", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="ms", 
                        `title`="Mean Square", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisCoef",
                title="Coefficients",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="response", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisRecommend",
                title="Preferred settings",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="response", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="goal", 
                        `title`="Goal", 
                        `type`="text"),
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Preferred level", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisHalfNormal",
                title="Half-Normal Plot",
                width=450,
                height=400,
                renderFun=".plotHalfNormal",
                visible="(evaluateDesign && halfNormal)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisPareto",
                title="Pareto Plot",
                width=450,
                height=400,
                renderFun=".plotPareto",
                visible="(evaluateDesign && pareto)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisMainEffects",
                title="Main Effects Plot",
                width=500,
                height=400,
                renderFun=".plotMainEffects",
                visible="(evaluateDesign && mainEffects)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisInteraction",
                title="Interaction Plot",
                width=450,
                height=400,
                renderFun=".plotInteraction",
                visible="(evaluateDesign && interaction)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisResiduals",
                title="Residual Plots",
                width=500,
                height=400,
                renderFun=".plotResiduals",
                visible="(evaluateDesign && residuals)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisContour",
                title="Contour Plot",
                width=450,
                height=400,
                renderFun=".plotContour",
                visible="(evaluateDesign && contour)",
                clearWith=list(
                    "evaluateDesign",
                    "model",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Output$new(
                options=options,
                name="designOutput",
                title="Spreadsheet columns",
                initInRun=TRUE))}))

customdesignBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "customdesignBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvdoe",
                name = "customdesign",
                version = c(1,0,0),
                options = options,
                results = customdesignResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Custom Design
#'
#' 
#' @param data .
#' @param factors .
#' @param model .
#' @param criterion .
#' @param nRuns .
#' @param replicates .
#' @param randomize .
#' @param seed .
#' @param responses .
#' @param responseTarget .
#' @param simulateResponses .
#' @param evaluateDesign .
#' @param halfNormal .
#' @param pareto .
#' @param mainEffects .
#' @param interaction .
#' @param residuals .
#' @param contour .
#' @param addToSpreadsheet .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$efficiency} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$analysisInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$analysisAnova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisCoef} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisRecommend} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisHalfNormal} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisPareto} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisMainEffects} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisInteraction} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisResiduals} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$designOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$design$asDF}
#'
#' \code{as.data.frame(results$design)}
#'
#' @export
customdesign <- function(
    data,
    factors = list(),
    model = "main",
    criterion = "D",
    nRuns = 12,
    replicates = 1,
    randomize = TRUE,
    seed = 1,
    responses = list(),
    responseTarget = 0,
    simulateResponses = TRUE,
    evaluateDesign = FALSE,
    halfNormal = TRUE,
    pareto = TRUE,
    mainEffects = FALSE,
    interaction = FALSE,
    residuals = TRUE,
    contour = FALSE,
    addToSpreadsheet = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("customdesign requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- customdesignOptions$new(
        factors = factors,
        model = model,
        criterion = criterion,
        nRuns = nRuns,
        replicates = replicates,
        randomize = randomize,
        seed = seed,
        responses = responses,
        responseTarget = responseTarget,
        simulateResponses = simulateResponses,
        evaluateDesign = evaluateDesign,
        halfNormal = halfNormal,
        pareto = pareto,
        mainEffects = mainEffects,
        interaction = interaction,
        residuals = residuals,
        contour = contour,
        addToSpreadsheet = addToSpreadsheet)

    analysis <- customdesignClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

