
# This file is automatically generated, you probably don't want to edit this

customdesignOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "customdesignOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factors = list(),
            model = "main",
            criterion = "D",
            nRuns = 12,
            replicates = 1,
            randomize = TRUE,
            seed = 1,
            responses = list(),
            responseTarget = 0,
            simulateResponses = TRUE, ...) {

            super$initialize(
                package="jmvdoe",
                name="customdesign",
                requiresData=TRUE,
                ...)

            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "continuous",
                                "categorical"),
                            default="continuous"),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL,
                            default="-1, 1"))))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "main",
                    "main2fi",
                    "rsm"),
                default="main")
            private$..criterion <- jmvcore::OptionList$new(
                "criterion",
                criterion,
                options=list(
                    "D",
                    "I"),
                default="D")
            private$..nRuns <- jmvcore::OptionInteger$new(
                "nRuns",
                nRuns,
                min=4,
                default=12)
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                min=1,
                default=1)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize,
                default=TRUE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=1)
            private$..responses <- jmvcore::OptionArray$new(
                "responses",
                responses,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "responses",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionList$new(
                            "goal",
                            NULL,
                            options=list(
                                "maximize",
                                "minimize",
                                "match"),
                            default="maximize"),
                        jmvcore::OptionNumber$new(
                            "target",
                            NULL,
                            default=0))))
            private$..responseTarget <- jmvcore::OptionNumber$new(
                "responseTarget",
                responseTarget,
                default=0,
                hidden=TRUE)
            private$..simulateResponses <- jmvcore::OptionBool$new(
                "simulateResponses",
                simulateResponses,
                default=TRUE)
            private$..designOutput <- jmvcore::OptionOutput$new(
                "designOutput")

            self$.addOption(private$..factors)
            self$.addOption(private$..model)
            self$.addOption(private$..criterion)
            self$.addOption(private$..nRuns)
            self$.addOption(private$..replicates)
            self$.addOption(private$..randomize)
            self$.addOption(private$..seed)
            self$.addOption(private$..responses)
            self$.addOption(private$..responseTarget)
            self$.addOption(private$..simulateResponses)
            self$.addOption(private$..designOutput)
        }),
    active = list(
        factors = function() private$..factors$value,
        model = function() private$..model$value,
        criterion = function() private$..criterion$value,
        nRuns = function() private$..nRuns$value,
        replicates = function() private$..replicates$value,
        randomize = function() private$..randomize$value,
        seed = function() private$..seed$value,
        responses = function() private$..responses$value,
        responseTarget = function() private$..responseTarget$value,
        simulateResponses = function() private$..simulateResponses$value,
        designOutput = function() private$..designOutput$value),
    private = list(
        ..factors = NA,
        ..model = NA,
        ..criterion = NA,
        ..nRuns = NA,
        ..replicates = NA,
        ..randomize = NA,
        ..seed = NA,
        ..responses = NA,
        ..responseTarget = NA,
        ..simulateResponses = NA,
        ..designOutput = NA)
)

customdesignResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "customdesignResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        design = function() private$.items[["design"]],
        efficiency = function() private$.items[["efficiency"]],
        designOutput = function() private$.items[["designOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Custom Design")
            self$add(jmvcore::Html$new(
                options=options,
                name="info",
                title="Design Summary",
                clearWith=list(
                    "factors",
                    "model",
                    "criterion",
                    "nRuns",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Table$new(
                options=options,
                name="design",
                title="Design Table",
                clearWith=list(
                    "factors",
                    "model",
                    "criterion",
                    "nRuns",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="Run", 
                        `title`="Run", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="efficiency",
                title="Design Efficiency",
                clearWith=list(
                    "factors",
                    "model",
                    "criterion",
                    "nRuns",
                    "randomize",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="designOutput",
                title="Spreadsheet columns",
                initInRun=TRUE))}))

customdesignBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "customdesignBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvdoe",
                name = "customdesign",
                version = c(1,0,0),
                options = options,
                results = customdesignResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Custom Design
#'
#' Generate a custom optimal design when a standard factorial, screening, or 
#' response-surface array does not fit the run budget or factor mix. Choose a 
#' model (mains, two-factor interactions, or quadratic) and D- or 
#' I-optimality, then write the runs to the spreadsheet.
#' @param data .
#' @param factors .
#' @param model .
#' @param criterion .
#' @param nRuns .
#' @param replicates .
#' @param randomize .
#' @param seed .
#' @param responses .
#' @param responseTarget .
#' @param simulateResponses .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$efficiency} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$designOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$design$asDF}
#'
#' \code{as.data.frame(results$design)}
#'
#' @export
customdesign <- function(
    data,
    factors = list(),
    model = "main",
    criterion = "D",
    nRuns = 12,
    replicates = 1,
    randomize = TRUE,
    seed = 1,
    responses = list(),
    responseTarget = 0,
    simulateResponses = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("customdesign requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- customdesignOptions$new(
        factors = factors,
        model = model,
        criterion = criterion,
        nRuns = nRuns,
        replicates = replicates,
        randomize = randomize,
        seed = seed,
        responses = responses,
        responseTarget = responseTarget,
        simulateResponses = simulateResponses)

    analysis <- customdesignClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

