
# This file is automatically generated, you probably don't want to edit this

fullfactorialOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fullfactorialOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factors = list(),
            replicates = 1,
            randomize = TRUE,
            seed = 1,
            responses = list(),
            responseTarget = 0,
            simulateResponses = TRUE, ...) {

            super$initialize(
                package="jmvdoe",
                name="fullfactorial",
                requiresData=TRUE,
                ...)

            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL,
                            default="-1, 1"))))
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                min=1,
                default=1)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize,
                default=TRUE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=1)
            private$..responses <- jmvcore::OptionArray$new(
                "responses",
                responses,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "responses",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionList$new(
                            "goal",
                            NULL,
                            options=list(
                                "maximize",
                                "minimize",
                                "match"),
                            default="maximize"),
                        jmvcore::OptionNumber$new(
                            "target",
                            NULL,
                            default=0))))
            private$..responseTarget <- jmvcore::OptionNumber$new(
                "responseTarget",
                responseTarget,
                default=0,
                hidden=TRUE)
            private$..simulateResponses <- jmvcore::OptionBool$new(
                "simulateResponses",
                simulateResponses,
                default=TRUE)
            private$..designOutput <- jmvcore::OptionOutput$new(
                "designOutput")

            self$.addOption(private$..factors)
            self$.addOption(private$..replicates)
            self$.addOption(private$..randomize)
            self$.addOption(private$..seed)
            self$.addOption(private$..responses)
            self$.addOption(private$..responseTarget)
            self$.addOption(private$..simulateResponses)
            self$.addOption(private$..designOutput)
        }),
    active = list(
        factors = function() private$..factors$value,
        replicates = function() private$..replicates$value,
        randomize = function() private$..randomize$value,
        seed = function() private$..seed$value,
        responses = function() private$..responses$value,
        responseTarget = function() private$..responseTarget$value,
        simulateResponses = function() private$..simulateResponses$value,
        designOutput = function() private$..designOutput$value),
    private = list(
        ..factors = NA,
        ..replicates = NA,
        ..randomize = NA,
        ..seed = NA,
        ..responses = NA,
        ..responseTarget = NA,
        ..simulateResponses = NA,
        ..designOutput = NA)
)

fullfactorialResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fullfactorialResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        design = function() private$.items[["design"]],
        designOutput = function() private$.items[["designOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Full Factorial Design")
            self$add(jmvcore::Html$new(
                options=options,
                name="info",
                title="Design Summary",
                clearWith=list(
                    "factors",
                    "replicates",
                    "randomize",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Table$new(
                options=options,
                name="design",
                title="Design Table",
                clearWith=list(
                    "factors",
                    "replicates",
                    "randomize",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="Run", 
                        `title`="Run", 
                        `type`="text"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="designOutput",
                title="Spreadsheet columns",
                initInRun=TRUE))}))

fullfactorialBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fullfactorialBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvdoe",
                name = "fullfactorial",
                version = c(1,0,0),
                options = options,
                results = fullfactorialResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Full Factorial Design
#'
#' Generate a full factorial design for factors with two or more levels, 
#' including mixed-level designs. Optionally randomize the run order, 
#' replicate the whole design, add response columns, and write the runs to the 
#' spreadsheet. After you measure the responses, fit a model with Analyze 
#' Design.
#' @param data .
#' @param factors .
#' @param replicates .
#' @param randomize .
#' @param seed .
#' @param responses .
#' @param responseTarget .
#' @param simulateResponses .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$designOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$design$asDF}
#'
#' \code{as.data.frame(results$design)}
#'
#' @export
fullfactorial <- function(
    data,
    factors = list(),
    replicates = 1,
    randomize = TRUE,
    seed = 1,
    responses = list(),
    responseTarget = 0,
    simulateResponses = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("fullfactorial requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- fullfactorialOptions$new(
        factors = factors,
        replicates = replicates,
        randomize = randomize,
        seed = seed,
        responses = responses,
        responseTarget = responseTarget,
        simulateResponses = simulateResponses)

    analysis <- fullfactorialClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

