
# This file is automatically generated, you probably don't want to edit this

screeningOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "screeningOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factors = list(),
            designType = "frf2",
            nRuns = 8,
            centerPoints = 0,
            replicates = 1,
            randomize = TRUE,
            seed = 1,
            responses = list(),
            responseTarget = 0,
            simulateResponses = TRUE, ...) {

            super$initialize(
                package="jmvdoe",
                name="screening",
                requiresData=TRUE,
                ...)

            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL,
                            default="-1, 1"))))
            private$..designType <- jmvcore::OptionList$new(
                "designType",
                designType,
                options=list(
                    "frf2",
                    "pb"),
                default="frf2")
            private$..nRuns <- jmvcore::OptionInteger$new(
                "nRuns",
                nRuns,
                min=4,
                default=8)
            private$..centerPoints <- jmvcore::OptionInteger$new(
                "centerPoints",
                centerPoints,
                min=0,
                default=0)
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                min=1,
                default=1)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize,
                default=TRUE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=1)
            private$..responses <- jmvcore::OptionArray$new(
                "responses",
                responses,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "responses",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionList$new(
                            "goal",
                            NULL,
                            options=list(
                                "maximize",
                                "minimize",
                                "match"),
                            default="maximize"),
                        jmvcore::OptionNumber$new(
                            "target",
                            NULL,
                            default=0))))
            private$..responseTarget <- jmvcore::OptionNumber$new(
                "responseTarget",
                responseTarget,
                default=0,
                hidden=TRUE)
            private$..simulateResponses <- jmvcore::OptionBool$new(
                "simulateResponses",
                simulateResponses,
                default=TRUE)
            private$..designOutput <- jmvcore::OptionOutput$new(
                "designOutput")

            self$.addOption(private$..factors)
            self$.addOption(private$..designType)
            self$.addOption(private$..nRuns)
            self$.addOption(private$..centerPoints)
            self$.addOption(private$..replicates)
            self$.addOption(private$..randomize)
            self$.addOption(private$..seed)
            self$.addOption(private$..responses)
            self$.addOption(private$..responseTarget)
            self$.addOption(private$..simulateResponses)
            self$.addOption(private$..designOutput)
        }),
    active = list(
        factors = function() private$..factors$value,
        designType = function() private$..designType$value,
        nRuns = function() private$..nRuns$value,
        centerPoints = function() private$..centerPoints$value,
        replicates = function() private$..replicates$value,
        randomize = function() private$..randomize$value,
        seed = function() private$..seed$value,
        responses = function() private$..responses$value,
        responseTarget = function() private$..responseTarget$value,
        simulateResponses = function() private$..simulateResponses$value,
        designOutput = function() private$..designOutput$value),
    private = list(
        ..factors = NA,
        ..designType = NA,
        ..nRuns = NA,
        ..centerPoints = NA,
        ..replicates = NA,
        ..randomize = NA,
        ..seed = NA,
        ..responses = NA,
        ..responseTarget = NA,
        ..simulateResponses = NA,
        ..designOutput = NA)
)

screeningResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "screeningResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        design = function() private$.items[["design"]],
        alias = function() private$.items[["alias"]],
        designOutput = function() private$.items[["designOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Screening Design")
            self$add(jmvcore::Html$new(
                options=options,
                name="info",
                title="Design Summary",
                clearWith=list(
                    "factors",
                    "designType",
                    "nRuns",
                    "centerPoints",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Table$new(
                options=options,
                name="design",
                title="Design Table",
                clearWith=list(
                    "factors",
                    "designType",
                    "nRuns",
                    "centerPoints",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="Run", 
                        `title`="Run", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="alias",
                title="Alias Structure",
                clearWith=list(
                    "factors",
                    "designType",
                    "nRuns",
                    "centerPoints",
                    "randomize",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="designOutput",
                title="Spreadsheet columns",
                initInRun=TRUE))}))

screeningBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "screeningBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvdoe",
                name = "screening",
                version = c(1,0,0),
                options = options,
                results = screeningResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Screening Design
#'
#' Generate a two-level screening design to find which factors matter with 
#' relatively few runs. Choose a regular fractional factorial (FrF2) or a 
#' Plackett-Burman array, set the number of runs and optional centre points, 
#' then write the design to the spreadsheet. Fit the measured results with 
#' Analyze Design.
#' @param data .
#' @param factors .
#' @param designType .
#' @param nRuns .
#' @param centerPoints .
#' @param replicates .
#' @param randomize .
#' @param seed .
#' @param responses .
#' @param responseTarget .
#' @param simulateResponses .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$alias} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$designOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$design$asDF}
#'
#' \code{as.data.frame(results$design)}
#'
#' @export
screening <- function(
    data,
    factors = list(),
    designType = "frf2",
    nRuns = 8,
    centerPoints = 0,
    replicates = 1,
    randomize = TRUE,
    seed = 1,
    responses = list(),
    responseTarget = 0,
    simulateResponses = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("screening requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- screeningOptions$new(
        factors = factors,
        designType = designType,
        nRuns = nRuns,
        centerPoints = centerPoints,
        replicates = replicates,
        randomize = randomize,
        seed = seed,
        responses = responses,
        responseTarget = responseTarget,
        simulateResponses = simulateResponses)

    analysis <- screeningClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

