
# This file is automatically generated, you probably don't want to edit this

taguchiarraysOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiarraysOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            arrayId = "L8.2.7",
            factors = list(),
            useOuter = FALSE,
            noiseFactors = list(),
            replicates = 2,
            randomize = TRUE,
            seed = 1,
            responses = list(),
            responseTarget = 0,
            simulateResponses = TRUE, ...) {

            super$initialize(
                package="jmvdoe",
                name="taguchiarrays",
                requiresData=TRUE,
                ...)

            private$..arrayId <- jmvcore::OptionList$new(
                "arrayId",
                arrayId,
                options=list(
                    "L4.2.3",
                    "L8.2.7",
                    "L9.3.4",
                    "L12.2.11",
                    "L16.2.15",
                    "L16.4.5",
                    "L18.2.1.3.7",
                    "L27.3.13",
                    "L32.2.31"),
                default="L8.2.7")
            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL,
                            default="1, 2"))))
            private$..useOuter <- jmvcore::OptionBool$new(
                "useOuter",
                useOuter,
                default=FALSE)
            private$..noiseFactors <- jmvcore::OptionArray$new(
                "noiseFactors",
                noiseFactors,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "noiseFactors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL,
                            default="Low, High"))))
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                min=2,
                default=2)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize,
                default=TRUE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=1)
            private$..responses <- jmvcore::OptionArray$new(
                "responses",
                responses,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "responses",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionList$new(
                            "goal",
                            NULL,
                            options=list(
                                "maximize",
                                "minimize",
                                "match"),
                            default="maximize"),
                        jmvcore::OptionNumber$new(
                            "target",
                            NULL,
                            default=0))))
            private$..responseTarget <- jmvcore::OptionNumber$new(
                "responseTarget",
                responseTarget,
                default=0,
                hidden=TRUE)
            private$..simulateResponses <- jmvcore::OptionBool$new(
                "simulateResponses",
                simulateResponses,
                default=TRUE)
            private$..designOutput <- jmvcore::OptionOutput$new(
                "designOutput")

            self$.addOption(private$..arrayId)
            self$.addOption(private$..factors)
            self$.addOption(private$..useOuter)
            self$.addOption(private$..noiseFactors)
            self$.addOption(private$..replicates)
            self$.addOption(private$..randomize)
            self$.addOption(private$..seed)
            self$.addOption(private$..responses)
            self$.addOption(private$..responseTarget)
            self$.addOption(private$..simulateResponses)
            self$.addOption(private$..designOutput)
        }),
    active = list(
        arrayId = function() private$..arrayId$value,
        factors = function() private$..factors$value,
        useOuter = function() private$..useOuter$value,
        noiseFactors = function() private$..noiseFactors$value,
        replicates = function() private$..replicates$value,
        randomize = function() private$..randomize$value,
        seed = function() private$..seed$value,
        responses = function() private$..responses$value,
        responseTarget = function() private$..responseTarget$value,
        simulateResponses = function() private$..simulateResponses$value,
        designOutput = function() private$..designOutput$value),
    private = list(
        ..arrayId = NA,
        ..factors = NA,
        ..useOuter = NA,
        ..noiseFactors = NA,
        ..replicates = NA,
        ..randomize = NA,
        ..seed = NA,
        ..responses = NA,
        ..responseTarget = NA,
        ..simulateResponses = NA,
        ..designOutput = NA)
)

taguchiarraysResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiarraysResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        design = function() private$.items[["design"]],
        designOutput = function() private$.items[["designOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Taguchi Arrays")
            self$add(jmvcore::Html$new(
                options=options,
                name="info",
                title="Design Summary",
                clearWith=list(
                    "arrayId",
                    "factors",
                    "useOuter",
                    "noiseFactors",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Table$new(
                options=options,
                name="design",
                title="Design Table",
                clearWith=list(
                    "arrayId",
                    "factors",
                    "useOuter",
                    "noiseFactors",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="Run", 
                        `title`="Run", 
                        `type`="text"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="designOutput",
                title="Spreadsheet columns",
                initInRun=TRUE))}))

taguchiarraysBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiarraysBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvdoe",
                name = "taguchiarrays",
                version = c(1,0,0),
                options = options,
                results = taguchiarraysResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Taguchi Arrays
#'
#' Generate a Taguchi orthogonal array for control factors, with an optional 
#' outer / noise array. The inner array is written at least twice so S/N ANOVA 
#' has residual degrees of freedom without pooling a factor. After the 
#' experiment, fit the measured results with Analyze Design.
#' @param data .
#' @param arrayId .
#' @param factors .
#' @param useOuter .
#' @param noiseFactors .
#' @param replicates copies of the inner array; at least two so S/N ANOVA has
#'   residual degrees of freedom without pooling a factor
#' @param randomize .
#' @param seed .
#' @param responses .
#' @param responseTarget .
#' @param simulateResponses .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$designOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$design$asDF}
#'
#' \code{as.data.frame(results$design)}
#'
#' @export
taguchiarrays <- function(
    data,
    arrayId = "L8.2.7",
    factors = list(),
    useOuter = FALSE,
    noiseFactors = list(),
    replicates = 2,
    randomize = TRUE,
    seed = 1,
    responses = list(),
    responseTarget = 0,
    simulateResponses = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("taguchiarrays requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- taguchiarraysOptions$new(
        arrayId = arrayId,
        factors = factors,
        useOuter = useOuter,
        noiseFactors = noiseFactors,
        replicates = replicates,
        randomize = randomize,
        seed = seed,
        responses = responses,
        responseTarget = responseTarget,
        simulateResponses = simulateResponses)

    analysis <- taguchiarraysClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

