
# This file is automatically generated, you probably don't want to edit this

taguchiarraysOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiarraysOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            arrayId = "L8.2.7",
            factors = list(),
            useOuter = FALSE,
            noiseFactors = list(),
            replicates = 1,
            randomize = TRUE,
            seed = 1,
            responses = list(),
            responseTarget = 0,
            simulateResponses = TRUE,
            evaluateDesign = FALSE,
            snType = "smaller",
            snModel = TRUE,
            plotSN = TRUE,
            plotMeans = TRUE,
            addToSpreadsheet = FALSE, ...) {

            super$initialize(
                package="jmvdoe",
                name="taguchiarrays",
                requiresData=TRUE,
                ...)

            private$..arrayId <- jmvcore::OptionList$new(
                "arrayId",
                arrayId,
                options=list(
                    "L4.2.3",
                    "L8.2.7",
                    "L9.3.4",
                    "L12.2.11",
                    "L16.2.15",
                    "L16.4.5",
                    "L18.2.1.3.7",
                    "L27.3.13",
                    "L32.2.31"),
                default="L8.2.7")
            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL,
                            default="1, 2"))))
            private$..useOuter <- jmvcore::OptionBool$new(
                "useOuter",
                useOuter,
                default=FALSE)
            private$..noiseFactors <- jmvcore::OptionArray$new(
                "noiseFactors",
                noiseFactors,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "noiseFactors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL,
                            default="Low, High"))))
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                min=1,
                default=1)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize,
                default=TRUE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=1)
            private$..responses <- jmvcore::OptionArray$new(
                "responses",
                responses,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "responses",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL,
                            default=""),
                        jmvcore::OptionList$new(
                            "goal",
                            NULL,
                            options=list(
                                "maximize",
                                "minimize",
                                "match"),
                            default="maximize"),
                        jmvcore::OptionNumber$new(
                            "target",
                            NULL,
                            default=0))))
            private$..responseTarget <- jmvcore::OptionNumber$new(
                "responseTarget",
                responseTarget,
                default=0,
                hidden=TRUE)
            private$..simulateResponses <- jmvcore::OptionBool$new(
                "simulateResponses",
                simulateResponses,
                default=TRUE)
            private$..evaluateDesign <- jmvcore::OptionBool$new(
                "evaluateDesign",
                evaluateDesign,
                default=FALSE)
            private$..snType <- jmvcore::OptionList$new(
                "snType",
                snType,
                hidden=TRUE,
                options=list(
                    "smaller",
                    "larger",
                    "nominal"),
                default="smaller")
            private$..snModel <- jmvcore::OptionBool$new(
                "snModel",
                snModel,
                default=TRUE)
            private$..plotSN <- jmvcore::OptionBool$new(
                "plotSN",
                plotSN,
                default=TRUE)
            private$..plotMeans <- jmvcore::OptionBool$new(
                "plotMeans",
                plotMeans,
                default=TRUE)
            private$..addToSpreadsheet <- jmvcore::OptionAction$new(
                "addToSpreadsheet",
                addToSpreadsheet)
            private$..designOutput <- jmvcore::OptionOutput$new(
                "designOutput")

            self$.addOption(private$..arrayId)
            self$.addOption(private$..factors)
            self$.addOption(private$..useOuter)
            self$.addOption(private$..noiseFactors)
            self$.addOption(private$..replicates)
            self$.addOption(private$..randomize)
            self$.addOption(private$..seed)
            self$.addOption(private$..responses)
            self$.addOption(private$..responseTarget)
            self$.addOption(private$..simulateResponses)
            self$.addOption(private$..evaluateDesign)
            self$.addOption(private$..snType)
            self$.addOption(private$..snModel)
            self$.addOption(private$..plotSN)
            self$.addOption(private$..plotMeans)
            self$.addOption(private$..addToSpreadsheet)
            self$.addOption(private$..designOutput)
        }),
    active = list(
        arrayId = function() private$..arrayId$value,
        factors = function() private$..factors$value,
        useOuter = function() private$..useOuter$value,
        noiseFactors = function() private$..noiseFactors$value,
        replicates = function() private$..replicates$value,
        randomize = function() private$..randomize$value,
        seed = function() private$..seed$value,
        responses = function() private$..responses$value,
        responseTarget = function() private$..responseTarget$value,
        simulateResponses = function() private$..simulateResponses$value,
        evaluateDesign = function() private$..evaluateDesign$value,
        snType = function() private$..snType$value,
        snModel = function() private$..snModel$value,
        plotSN = function() private$..plotSN$value,
        plotMeans = function() private$..plotMeans$value,
        addToSpreadsheet = function() private$..addToSpreadsheet$value,
        designOutput = function() private$..designOutput$value),
    private = list(
        ..arrayId = NA,
        ..factors = NA,
        ..useOuter = NA,
        ..noiseFactors = NA,
        ..replicates = NA,
        ..randomize = NA,
        ..seed = NA,
        ..responses = NA,
        ..responseTarget = NA,
        ..simulateResponses = NA,
        ..evaluateDesign = NA,
        ..snType = NA,
        ..snModel = NA,
        ..plotSN = NA,
        ..plotMeans = NA,
        ..addToSpreadsheet = NA,
        ..designOutput = NA)
)

taguchiarraysResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiarraysResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        design = function() private$.items[["design"]],
        analysisInfo = function() private$.items[["analysisInfo"]],
        analysisRecommend = function() private$.items[["analysisRecommend"]],
        analysisPerRun = function() private$.items[["analysisPerRun"]],
        analysisResponseSN = function() private$.items[["analysisResponseSN"]],
        analysisResponseMean = function() private$.items[["analysisResponseMean"]],
        analysisSnAnova = function() private$.items[["analysisSnAnova"]],
        analysisPlotSN = function() private$.items[["analysisPlotSN"]],
        analysisPlotMeans = function() private$.items[["analysisPlotMeans"]],
        designOutput = function() private$.items[["designOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Taguchi Arrays")
            self$add(jmvcore::Html$new(
                options=options,
                name="info",
                title="Design Summary",
                clearWith=list(
                    "arrayId",
                    "factors",
                    "useOuter",
                    "noiseFactors",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses")))
            self$add(jmvcore::Table$new(
                options=options,
                name="design",
                title="Design Table",
                clearWith=list(
                    "arrayId",
                    "factors",
                    "useOuter",
                    "noiseFactors",
                    "randomize",
                    "seed",
                    "replicates",
                    "responses",
                    "responseTarget",
                    "simulateResponses"),
                columns=list(
                    list(
                        `name`="Run", 
                        `title`="Run", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="analysisInfo",
                title="Taguchi Summary",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "snType",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses",
                    "useOuter",
                    "noiseFactors")))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisRecommend",
                title="Preferred settings",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "snType",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses",
                    "useOuter",
                    "noiseFactors"),
                columns=list(
                    list(
                        `name`="response", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="goal", 
                        `title`="Goal", 
                        `type`="text"),
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Preferred level", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisPerRun",
                title="Per-run SN and Mean",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "snType",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses",
                    "useOuter",
                    "noiseFactors"),
                columns=list(
                    list(
                        `name`="run", 
                        `title`="Run", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sn", 
                        `title`="SN", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisResponseSN",
                title="Response Table (SN)",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "snType",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses",
                    "useOuter",
                    "noiseFactors"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="meanSN", 
                        `title`="Mean SN", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisResponseMean",
                title="Response Table (Means)",
                visible="(evaluateDesign)",
                clearWith=list(
                    "evaluateDesign",
                    "snType",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses",
                    "useOuter",
                    "noiseFactors"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="meanY", 
                        `title`="Mean Response", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisSnAnova",
                title="ANOVA on SN",
                visible="(evaluateDesign && snModel)",
                clearWith=list(
                    "evaluateDesign",
                    "snType",
                    "snModel",
                    "factors",
                    "replicates",
                    "seed",
                    "responses",
                    "responseTarget",
                    "simulateResponses",
                    "useOuter",
                    "noiseFactors"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="ss", 
                        `title`="Sum of Squares", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="ms", 
                        `title`="Mean Square", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisPlotSN",
                title="SN Main Effects",
                width=500,
                height=400,
                renderFun=".plotSN",
                visible="(evaluateDesign && plotSN)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="analysisPlotMeans",
                title="Means Main Effects",
                width=500,
                height=400,
                renderFun=".plotMeans",
                visible="(evaluateDesign && plotMeans)"))
            self$add(jmvcore::Output$new(
                options=options,
                name="designOutput",
                title="Spreadsheet columns",
                initInRun=TRUE))}))

taguchiarraysBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiarraysBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvdoe",
                name = "taguchiarrays",
                version = c(1,0,0),
                options = options,
                results = taguchiarraysResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Taguchi Arrays
#'
#' 
#' @param data .
#' @param arrayId .
#' @param factors .
#' @param useOuter .
#' @param noiseFactors .
#' @param replicates .
#' @param randomize .
#' @param seed .
#' @param responses .
#' @param responseTarget .
#' @param simulateResponses .
#' @param evaluateDesign .
#' @param snType .
#' @param snModel .
#' @param plotSN .
#' @param plotMeans .
#' @param addToSpreadsheet .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$analysisRecommend} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisPerRun} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisResponseSN} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisResponseMean} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisSnAnova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisPlotSN} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$analysisPlotMeans} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$designOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$design$asDF}
#'
#' \code{as.data.frame(results$design)}
#'
#' @export
taguchiarrays <- function(
    data,
    arrayId = "L8.2.7",
    factors = list(),
    useOuter = FALSE,
    noiseFactors = list(),
    replicates = 1,
    randomize = TRUE,
    seed = 1,
    responses = list(),
    responseTarget = 0,
    simulateResponses = TRUE,
    evaluateDesign = FALSE,
    snType = "smaller",
    snModel = TRUE,
    plotSN = TRUE,
    plotMeans = TRUE,
    addToSpreadsheet = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("taguchiarrays requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- taguchiarraysOptions$new(
        arrayId = arrayId,
        factors = factors,
        useOuter = useOuter,
        noiseFactors = noiseFactors,
        replicates = replicates,
        randomize = randomize,
        seed = seed,
        responses = responses,
        responseTarget = responseTarget,
        simulateResponses = simulateResponses,
        evaluateDesign = evaluateDesign,
        snType = snType,
        snModel = snModel,
        plotSN = plotSN,
        plotMeans = plotMeans,
        addToSpreadsheet = addToSpreadsheet)

    analysis <- taguchiarraysClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

